--------------------------------------------------------
--  File created - Wednesday-November-23-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "SMARTBOOK"."CATEGORY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SMARTBOOK.CATEGORY
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (1,'programming');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (2,'java');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (3,'php');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (4,'design patterns');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (5,'hibernate');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (6,'tools');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (7,'javascript');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (9,'xml');
Insert into SMARTBOOK.CATEGORY (ID,NAME) values (8,'extjs');
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTBOOK"."CATEGORY_PK" ON "SMARTBOOK"."CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "SMARTBOOK"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SMARTBOOK"."CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
